"""Reader for the .veblk block-analysis sidecar produced by veye_probe.

The sidecar is generated by the patched-FFmpeg helper (native/veye_probe.c).
It carries per-frame per-macroblock coding info (mb_type, QP) that mainline
FFmpeg does not expose. This module parses it and converts the codec
MB_TYPE bitmask into the codec-agnostic BLOCK_DTYPE partitions consumed by
the overlays.
"""

from __future__ import annotations

import os
import struct
from dataclasses import dataclass
from typing import Optional

import numpy as np

from .schema import BLOCK_DTYPE, MV_DTYPE, PredType

# Sidecar file header: u32 magic 'VEYE', u32 version, u32 n_frames
_FILE_MAGIC = 0x45594556  # bytes V E Y E
_FILE_HDR = struct.Struct("<III")
_ENTRY_HDR = struct.Struct("<II")  # frame_index, payload_size

# VeyeBlockInfoHeader: u32 magic 'VEBK', u16 ver, u16 rec_size, u32 codec_id,
#                      u32 grid_w, u32 grid_h, u32 block_unit, u32 n_records
_BLK_MAGIC = 0x4B424556  # bytes V E B K
_BLK_HDR = struct.Struct("<IHHIIIII")
# v4 HEVC: appended after the records -> u32 tu_grid_w, tu_grid_h, tu_unit,
# then tu_grid_w*tu_grid_h u8 luma-TU log2 sizes (0 = none, use CU size).
_TU_HDR = struct.Struct("<III")
# v5 HEVC: appended after the TU grid -> i32 own_poc, nb_l0, nb_l1, then
# 16 i32 L0 ref POCs and 16 i32 L1 ref POCs.
_MAX_REFS = 16
_REF_HDR = struct.Struct("<iii%di%di" % (_MAX_REFS, _MAX_REFS))
# v6 HEVC: appended after the ref section -> u32 ctb_size, ctb_w, ctb_h,
# num_tile_cols, num_tile_rows, then ctb_w*ctb_h i32 slice ids (CTB raster),
# then (num_tile_cols+1) u32 tile column x-boundaries and (num_tile_rows+1)
# u32 tile row y-boundaries, all in pixels.
_STRUCT_HDR = struct.Struct("<IIIII")
# VeyeBlockRecord (H.264): u32 mb_type, i32 qp
_REC = np.dtype([("mb_type", "<u4"), ("qp", "<i4")])
# VeyeBlockRecordHEVC (sidecar v2): u8 cu_log2, u8 pred, u8 intra_mode,
# u8 pred_flag, i32 qp, i16 mv0_x/y, i16 mv1_x/y, i8 ref0/ref1, u16 reserved.
_REC_HEVC = np.dtype([
    ("cu_log2", "u1"), ("pred", "u1"), ("intra_mode", "u1"),
    ("pred_flag", "u1"), ("qp", "<i4"),
    ("mv0_x", "<i2"), ("mv0_y", "<i2"), ("mv1_x", "<i2"), ("mv1_y", "<i2"),
    ("ref0", "i1"), ("ref1", "i1"), ("part_mode", "u1"), ("ct_depth", "u1"),
])

# VeyeBlockRecordAV1 (sidecar v2): u8 bsize, pred, mode, skip, i32 qp,
# i16 mv0_x/y, i16 mv1_x/y, i8 ref0/ref1, u8 tx_size, u8 reserved (20 bytes).
_REC_AV1 = np.dtype([
    ("bsize", "u1"), ("pred", "u1"), ("mode", "u1"), ("skip", "u1"),
    ("qp", "<i4"),
    ("mv0_x", "<i2"), ("mv0_y", "<i2"), ("mv1_x", "<i2"), ("mv1_y", "<i2"),
    ("ref0", "i1"), ("ref1", "i1"), ("tx_size", "u1"), ("reserved", "u1"),
])

# HEVC motion vectors are stored in quarter-pel luma units.
_HEVC_MV_SCALE = 4.0
# AV1 motion vectors are stored in eighth-pel luma units.
_AV1_MV_SCALE = 8.0

# codec_id values written into the header (AVCodecID, ABI-stable in practice).
_CODEC_H264 = 27
_CODEC_HEVC = 173
_CODEC_AV1 = 225

# libaom BLOCK_SIZE enum -> (luma width, height) px, indexed 0..BLOCK_SIZES_ALL-1.
_AV1_BSIZE_WH = (
    (4, 4), (4, 8), (8, 4), (8, 8), (8, 16), (16, 8), (16, 16), (16, 32),
    (32, 16), (32, 32), (32, 64), (64, 32), (64, 64), (64, 128), (128, 64),
    (128, 128), (4, 16), (16, 4), (8, 32), (32, 8), (16, 64), (64, 16),
)

# libaom TX_SIZE enum -> (luma width, height) px, indexed 0..TX_SIZES_ALL-1.
_AV1_TXSIZE_WH = (
    (4, 4), (8, 8), (16, 16), (32, 32), (64, 64),
    (4, 8), (8, 4), (8, 16), (16, 8), (16, 32), (32, 16),
    (32, 64), (64, 32), (4, 16), (16, 4), (8, 32), (32, 8),
    (16, 64), (64, 16),
)

# FFmpeg MB_TYPE_* bits (libavcodec/mpegutils.h) — ABI-stable.
MB_TYPE_INTRA4x4 = 1 << 0
MB_TYPE_INTRA16x16 = 1 << 1
MB_TYPE_INTRA_PCM = 1 << 2
MB_TYPE_16x16 = 1 << 3
MB_TYPE_16x8 = 1 << 4
MB_TYPE_8x16 = 1 << 5
MB_TYPE_8x8 = 1 << 6
MB_TYPE_DIRECT2 = 1 << 8
MB_TYPE_P0L0 = 1 << 12
MB_TYPE_P1L0 = 1 << 13
MB_TYPE_P0L1 = 1 << 14
MB_TYPE_P1L1 = 1 << 15
MB_TYPE_SKIP = 1 << 17

_MB_TYPE_INTRA = MB_TYPE_INTRA4x4 | MB_TYPE_INTRA16x16 | MB_TYPE_INTRA_PCM
_MB_TYPE_L0 = MB_TYPE_P0L0 | MB_TYPE_P1L0
_MB_TYPE_L1 = MB_TYPE_P0L1 | MB_TYPE_P1L1

# Partition shape codes stored in BLOCK_DTYPE["mode"] for labeling.
SHAPE_16x16, SHAPE_16x8, SHAPE_8x16, SHAPE_8x8 = 0, 1, 2, 3
SHAPE_INTRA16, SHAPE_INTRA4, SHAPE_IPCM, SHAPE_SKIP, SHAPE_DIRECT = 4, 5, 6, 7, 8


@dataclass
class VeyeFrameBlocks:
    """Raw per-cell grid for one frame.

    H.264 cells are 16x16 macroblocks carrying an mb_type bitmask. HEVC
    cells are min coding blocks (typically 8x8); the variable CU size and
    prediction class live in the cu_log2/pred/intra_mode grids instead.
    """
    codec_id: int
    grid_w: int
    grid_h: int
    block_unit: int
    qp: np.ndarray                          # int32, shape (grid_h, grid_w)
    mb_type: Optional[np.ndarray] = None    # H.264: uint32 grid
    cu_log2: Optional[np.ndarray] = None    # HEVC: log2 CU size px
    pred: Optional[np.ndarray] = None       # HEVC: PredType per cell
    intra_mode: Optional[np.ndarray] = None  # HEVC: luma intra mode 0..34
    pred_flag: Optional[np.ndarray] = None  # HEVC: PredFlag (0/1/2/3 = I/L0/L1/BI)
    part_mode: Optional[np.ndarray] = None  # HEVC: PartMode per cell (0..7)
    ct_depth: Optional[np.ndarray] = None   # HEVC: CU coding-tree depth (0=CTB)
    tu_log2: Optional[np.ndarray] = None    # HEVC: luma TU log2 per min-TB (0=none)
    tu_unit: int = 0                        # HEVC: pixels per min-TB cell
    own_poc: Optional[int] = None           # HEVC: this frame's POC (v5)
    ref_l0: tuple = ()                      # HEVC: L0 reference POCs
    ref_l1: tuple = ()                      # HEVC: L1 reference POCs
    ctb_size: int = 0                       # HEVC: luma CTB size px (v6)
    slice_grid: Optional[np.ndarray] = None  # HEVC: (ctb_h, ctb_w) i32 slice id
    tile_col_bd: tuple = ()                 # HEVC: tile column x-boundaries (px)
    tile_row_bd: tuple = ()                 # HEVC: tile row y-boundaries (px)
    mv: Optional[np.ndarray] = None         # HEVC/AV1: int16 grid (h, w, 2 lists, 2 xy)
    ref_idx: Optional[np.ndarray] = None    # HEVC/AV1: int8 grid (h, w, 2 lists)
    bsize: Optional[np.ndarray] = None      # AV1: BLOCK_SIZE enum per 4x4 MI cell
    mode: Optional[np.ndarray] = None       # AV1: PREDICTION_MODE per cell
    skip: Optional[np.ndarray] = None       # AV1: skip_txfm flag per cell
    tx_size: Optional[np.ndarray] = None    # AV1: TX_SIZE per cell


def load_sidecar(path: str) -> Optional[dict[int, VeyeFrameBlocks]]:
    """Load a .veblk file into {frame_index: VeyeFrameBlocks}, or None."""
    try:
        with open(path, "rb") as f:
            data = f.read()
    except OSError:
        return None
    if len(data) < _FILE_HDR.size:
        return None
    magic, _ver, n_frames = _FILE_HDR.unpack_from(data, 0)
    if magic != _FILE_MAGIC or n_frames <= 0:
        return None  # bad magic, or header not finalised (n_frames still 0)

    frames: dict[int, VeyeFrameBlocks] = {}
    off = _FILE_HDR.size
    for _ in range(n_frames):
        # Any truncation means the file is incomplete (e.g. an interrupted or
        # still-running helper): reject it so the caller regenerates rather
        # than trusting a partial frame set.
        if off + _ENTRY_HDR.size > len(data):
            return None
        frame_index, payload_size = _ENTRY_HDR.unpack_from(data, off)
        off += _ENTRY_HDR.size
        if off + payload_size > len(data):
            return None
        payload = data[off:off + payload_size]
        off += payload_size
        fb = _parse_payload(payload)
        if fb is not None:
            frames[frame_index] = fb
    return frames if frames else None


FILE_HEADER_SIZE = _FILE_HDR.size


def read_incremental(
    path: str, offset: int, header_ok: bool
) -> tuple[dict[int, VeyeFrameBlocks], int, bool]:
    """Parse frame entries appended to a .veblk that is still being written.

    Returns (new_frames, new_offset, header_ok). Only *complete* entries are
    decoded: the helper writes the file as a single sequential append, so the
    bytes on disk are always a valid prefix of the final stream, truncated at
    some byte. We stop at the first entry whose header or payload is not fully
    present yet and resume from there on the next call. The header's n_frames
    field is ignored (it stays 0 until the helper finishes); we read to EOF.

    `offset` is the number of bytes already consumed into complete entries
    (FILE_HEADER_SIZE once the header is validated). All file access is
    defensive: a missing file, a sharing violation, or a not-yet-written
    header simply yields no new frames and is retried later.
    """
    frames: dict[int, VeyeFrameBlocks] = {}
    try:
        size = os.path.getsize(path)
    except OSError:
        return frames, offset, header_ok

    if not header_ok:
        if size < _FILE_HDR.size:
            return frames, offset, False
        try:
            with open(path, "rb") as f:
                hdr = f.read(_FILE_HDR.size)
        except OSError:
            return frames, offset, False
        if len(hdr) < _FILE_HDR.size:
            return frames, offset, False
        magic, _ver, _n = _FILE_HDR.unpack(hdr)
        if magic != _FILE_MAGIC:
            return frames, offset, False
        header_ok = True
        offset = _FILE_HDR.size

    if size <= offset:
        return frames, offset, header_ok

    try:
        with open(path, "rb") as f:
            f.seek(offset)
            data = f.read()
    except OSError:
        return frames, offset, header_ok

    off, n = 0, len(data)
    while off + _ENTRY_HDR.size <= n:
        frame_index, payload_size = _ENTRY_HDR.unpack_from(data, off)
        end = off + _ENTRY_HDR.size + payload_size
        if end > n:
            break  # payload not fully written yet
        fb = _parse_payload(data[off + _ENTRY_HDR.size:end])
        if fb is not None:
            frames[frame_index] = fb
        off = end

    return frames, offset + off, header_ok


def _parse_payload(payload: bytes) -> Optional[VeyeFrameBlocks]:
    if len(payload) < _BLK_HDR.size:
        return None
    (magic, _ver, rec_size, codec_id,
     grid_w, grid_h, block_unit, n_records) = _BLK_HDR.unpack_from(payload, 0)
    if magic != _BLK_MAGIC or grid_w == 0 or grid_h == 0:
        return None
    if n_records != grid_w * grid_h:
        return None

    if codec_id == _CODEC_HEVC:
        recs = np.frombuffer(payload, dtype=_REC_HEVC, count=n_records,
                             offset=_BLK_HDR.size)
        mv = np.empty((grid_h, grid_w, 2, 2), dtype=np.int16)
        mv[..., 0, 0] = recs["mv0_x"].reshape(grid_h, grid_w)
        mv[..., 0, 1] = recs["mv0_y"].reshape(grid_h, grid_w)
        mv[..., 1, 0] = recs["mv1_x"].reshape(grid_h, grid_w)
        mv[..., 1, 1] = recs["mv1_y"].reshape(grid_h, grid_w)
        ref = np.empty((grid_h, grid_w, 2), dtype=np.int8)
        ref[..., 0] = recs["ref0"].reshape(grid_h, grid_w)
        ref[..., 1] = recs["ref1"].reshape(grid_h, grid_w)

        # v4: luma TU-size grid appended after the records (min-TB granularity).
        # v5: reference section appended after the TU grid.
        tu_log2 = None
        tu_unit = 0
        own_poc = None
        ref_l0: tuple = ()
        ref_l1: tuple = ()
        ctb_size = 0
        slice_grid = None
        tile_col_bd: tuple = ()
        tile_row_bd: tuple = ()
        if _ver >= 4:
            tu_off = _BLK_HDR.size + n_records * _REC_HEVC.itemsize
            if len(payload) >= tu_off + _TU_HDR.size:
                tw, th, tu_unit = _TU_HDR.unpack_from(payload, tu_off)
                g_off = tu_off + _TU_HDR.size
                if tw > 0 and th > 0 and len(payload) >= g_off + tw * th:
                    tu_log2 = np.frombuffer(
                        payload, dtype=np.uint8, count=tw * th, offset=g_off
                    ).reshape(th, tw).copy()
                ref_off = g_off + tw * th
                if _ver >= 5 and len(payload) >= ref_off + _REF_HDR.size:
                    vals = _REF_HDR.unpack_from(payload, ref_off)
                    own_poc = vals[0]
                    nb_l0, nb_l1 = vals[1], vals[2]
                    l0 = vals[3:3 + _MAX_REFS]
                    l1 = vals[3 + _MAX_REFS:3 + 2 * _MAX_REFS]
                    ref_l0 = tuple(l0[:max(0, nb_l0)])
                    ref_l1 = tuple(l1[:max(0, nb_l1)])
                # v6: picture-structure section after the ref section.
                st_off = ref_off + _REF_HDR.size
                if _ver >= 6 and len(payload) >= st_off + _STRUCT_HDR.size:
                    ctb_size, ctw, cth, ntc, ntr = _STRUCT_HDR.unpack_from(
                        payload, st_off)
                    grid_off = st_off + _STRUCT_HDR.size
                    n_ctb = ctw * cth
                    end = grid_off + n_ctb * 4 + (ntc + 1) * 4 + (ntr + 1) * 4
                    if ctw > 0 and cth > 0 and len(payload) >= end:
                        slice_grid = np.frombuffer(
                            payload, dtype="<i4", count=n_ctb, offset=grid_off
                        ).reshape(cth, ctw).copy()
                        cbd_off = grid_off + n_ctb * 4
                        rbd_off = cbd_off + (ntc + 1) * 4
                        tile_col_bd = tuple(np.frombuffer(
                            payload, dtype="<u4", count=ntc + 1, offset=cbd_off
                        ).tolist())
                        tile_row_bd = tuple(np.frombuffer(
                            payload, dtype="<u4", count=ntr + 1, offset=rbd_off
                        ).tolist())

        return VeyeFrameBlocks(
            codec_id, grid_w, grid_h, block_unit,
            qp=recs["qp"].reshape(grid_h, grid_w).copy(),
            cu_log2=recs["cu_log2"].reshape(grid_h, grid_w).copy(),
            pred=recs["pred"].reshape(grid_h, grid_w).copy(),
            intra_mode=recs["intra_mode"].reshape(grid_h, grid_w).copy(),
            pred_flag=recs["pred_flag"].reshape(grid_h, grid_w).copy(),
            part_mode=recs["part_mode"].reshape(grid_h, grid_w).copy(),
            ct_depth=recs["ct_depth"].reshape(grid_h, grid_w).copy(),
            tu_log2=tu_log2, tu_unit=tu_unit,
            own_poc=own_poc, ref_l0=ref_l0, ref_l1=ref_l1,
            ctb_size=ctb_size, slice_grid=slice_grid,
            tile_col_bd=tile_col_bd, tile_row_bd=tile_row_bd,
            mv=mv, ref_idx=ref,
        )

    if codec_id == _CODEC_AV1:
        recs = np.frombuffer(payload, dtype=_REC_AV1, count=n_records,
                             offset=_BLK_HDR.size)
        mv = np.empty((grid_h, grid_w, 2, 2), dtype=np.int16)
        mv[..., 0, 0] = recs["mv0_x"].reshape(grid_h, grid_w)
        mv[..., 0, 1] = recs["mv0_y"].reshape(grid_h, grid_w)
        mv[..., 1, 0] = recs["mv1_x"].reshape(grid_h, grid_w)
        mv[..., 1, 1] = recs["mv1_y"].reshape(grid_h, grid_w)
        ref = np.empty((grid_h, grid_w, 2), dtype=np.int8)
        ref[..., 0] = recs["ref0"].reshape(grid_h, grid_w)
        ref[..., 1] = recs["ref1"].reshape(grid_h, grid_w)
        # v5: reference section appended after the records. own_poc carries the
        # AV1 order hint of this output frame; ref_l0/ref_l1 are referenced
        # frames' order hints split into past/future. The decoder buffers each
        # decoded frame's grid by order hint and attaches the one matching the
        # output frame, so these are correctly associated even on reordered
        # streams (hierarchical B / altref).
        own_poc = None
        ref_l0: tuple = ()
        ref_l1: tuple = ()
        if _ver >= 5:
            ref_off = _BLK_HDR.size + n_records * _REC_AV1.itemsize
            if len(payload) >= ref_off + _REF_HDR.size:
                vals = _REF_HDR.unpack_from(payload, ref_off)
                own_poc = vals[0]
                nb_l0, nb_l1 = vals[1], vals[2]
                l0 = vals[3:3 + _MAX_REFS]
                l1 = vals[3 + _MAX_REFS:3 + 2 * _MAX_REFS]
                ref_l0 = tuple(l0[:max(0, nb_l0)])
                ref_l1 = tuple(l1[:max(0, nb_l1)])
        return VeyeFrameBlocks(
            codec_id, grid_w, grid_h, block_unit,
            qp=recs["qp"].reshape(grid_h, grid_w).copy(),
            pred=recs["pred"].reshape(grid_h, grid_w).copy(),
            bsize=recs["bsize"].reshape(grid_h, grid_w).copy(),
            mode=recs["mode"].reshape(grid_h, grid_w).copy(),
            skip=recs["skip"].reshape(grid_h, grid_w).copy(),
            tx_size=recs["tx_size"].reshape(grid_h, grid_w).copy(),
            mv=mv, ref_idx=ref,
            own_poc=own_poc, ref_l0=ref_l0, ref_l1=ref_l1,
        )

    recs = np.frombuffer(payload, dtype=_REC, count=n_records,
                         offset=_BLK_HDR.size)
    # v5 (H.264): reference section appended right after the records, mirroring
    # the HEVC layout (no TU grid for H.264).
    own_poc = None
    ref_l0: tuple = ()
    ref_l1: tuple = ()
    if _ver >= 5:
        ref_off = _BLK_HDR.size + n_records * _REC.itemsize
        if len(payload) >= ref_off + _REF_HDR.size:
            vals = _REF_HDR.unpack_from(payload, ref_off)
            own_poc = vals[0]
            nb_l0, nb_l1 = vals[1], vals[2]
            l0 = vals[3:3 + _MAX_REFS]
            l1 = vals[3 + _MAX_REFS:3 + 2 * _MAX_REFS]
            ref_l0 = tuple(l0[:max(0, nb_l0)])
            ref_l1 = tuple(l1[:max(0, nb_l1)])
    return VeyeFrameBlocks(
        codec_id, grid_w, grid_h, block_unit,
        qp=recs["qp"].reshape(grid_h, grid_w).copy(),
        mb_type=recs["mb_type"].reshape(grid_h, grid_w).copy(),
        own_poc=own_poc, ref_l0=ref_l0, ref_l1=ref_l1,
    )


def _pack(out: list, dtype) -> np.ndarray:
    """Build a structured array from a list of record tuples in one C-level
    conversion, instead of allocating and filling element-by-element."""
    if not out:
        return np.empty(0, dtype=dtype)
    return np.array(out, dtype=dtype)


def _mb_pred(t: int) -> int:
    """Prediction class of an H.264 macroblock from its mb_type bitmask."""
    if t & MB_TYPE_INTRA_PCM:
        return PredType.IPCM
    if t & _MB_TYPE_INTRA:
        return PredType.INTRA
    if t & MB_TYPE_SKIP:
        return PredType.SKIP
    if (t & _MB_TYPE_L0) and (t & _MB_TYPE_L1):
        return PredType.BI  # uses both reference lists
    return PredType.INTER


def blocks_from_frame(fb: VeyeFrameBlocks) -> np.ndarray:
    """Coding units (BLOCK_DTYPE). For H.264 the CU is the 16x16 macroblock;
    its prediction-partition split is the PU (see pus_from_frame)."""
    if fb.codec_id == _CODEC_HEVC:
        return _blocks_from_hevc(fb)
    if fb.codec_id == _CODEC_AV1:
        return _blocks_from_av1(fb)

    unit = fb.block_unit
    out: list[tuple] = []
    mb = fb.mb_type
    for my in range(fb.grid_h):
        py = my * unit
        for mx in range(fb.grid_w):
            t = int(mb[my, mx])
            out.append((mx * unit, py, unit, unit, 0, _mb_pred(t), 0))
    return _pack(out, BLOCK_DTYPE)


def _blocks_from_hevc(fb: VeyeFrameBlocks) -> np.ndarray:
    """Collapse the min-CB grid back into the HEVC coding-unit quadtree.

    Every min-CB cell carries the log2 size of the CU it belongs to. A CU
    is aligned to its own size, so the cell at the CU's top-left corner is
    the unique cell where both pixel coordinates are multiples of the CU
    size; we emit one partition rectangle there. The mode field stores
    cu_log2 for labeling.
    """
    unit = fb.block_unit
    gh, gw = fb.cu_log2.shape
    cl = fb.cu_log2.astype(np.int32)
    pred = fb.pred.astype(np.int32)
    pf = fb.pred_flag

    mx = np.arange(gw, dtype=np.int32)[None, :]
    my = np.arange(gh, dtype=np.int32)[:, None]
    span = np.maximum(1, (1 << cl) // unit)               # min-CB cells per CU
    origin = ((mx % span) == 0) & ((my % span) == 0)      # CU top-left cells
    ys, xs = np.nonzero(origin)
    if len(xs) == 0:
        return np.empty(0, dtype=BLOCK_DTYPE)

    clv = cl[ys, xs]
    cu_px = (1 << clv).astype(np.int32)
    p = pred[ys, xs].copy()
    if pf is not None:
        bi = (p == PredType.INTER) & (pf[ys, xs] == 3)    # PredFlag 3 = bi-pred
        p[bi] = PredType.BI
    depth = (fb.ct_depth[ys, xs] if fb.ct_depth is not None
             else np.zeros(len(xs), dtype=np.int32))

    out = np.empty(len(xs), dtype=BLOCK_DTYPE)
    out["x"] = xs * unit
    out["y"] = ys * unit
    out["w"] = cu_px
    out["h"] = cu_px
    out["depth"] = depth
    out["pred"] = p
    out["mode"] = clv
    return out


def _blocks_from_av1(fb: VeyeFrameBlocks) -> np.ndarray:
    """Collapse the 4x4 MI grid into AV1 coding blocks.

    ifd_inspect replicates the same mode-info across every 4x4 cell a coding
    block covers. Each AV1 block is aligned to its own (w, h), so the cell at
    the block's top-left corner is the unique cell whose pixel coordinates are
    multiples of the block dimensions; we emit one rectangle there. The mode
    field stores the libaom PREDICTION_MODE for labeling.
    """
    unit = fb.block_unit
    bsize = fb.bsize
    pred = fb.pred
    mode = fb.mode
    ref = fb.ref_idx
    out: list[tuple] = []
    for my in range(fb.grid_h):
        py = my * unit
        for mx in range(fb.grid_w):
            bs = int(bsize[my, mx])
            if bs < 0 or bs >= len(_AV1_BSIZE_WH):
                continue
            bw, bh = _AV1_BSIZE_WH[bs]
            px = mx * unit
            if px % bw or py % bh:
                continue  # not the top-left cell of this block
            p = int(pred[my, mx])
            # Compound prediction (a second reference) maps to BI, matching the
            # H.264/HEVC block-type coloring. AV1's skip_txfm flag is a residual
            # property (not a prediction mode like H.264/HEVC P_Skip), so it is
            # deliberately NOT folded into the prediction class here.
            if p == PredType.INTER and ref is not None and int(ref[my, mx, 1]) >= 1:
                p = PredType.BI
            out.append((px, py, bw, bh, 0, p, int(mode[my, mx])))
    return _pack(out, BLOCK_DTYPE)


# HEVC PartMode -> PU rectangles as (fx, fy, fw, fh) fractions of the CU.
_PART_PUS = {
    0: ((0.0, 0.0, 1.0, 1.0),),                                      # 2Nx2N
    1: ((0.0, 0.0, 1.0, 0.5), (0.0, 0.5, 1.0, 0.5)),                 # 2NxN
    2: ((0.0, 0.0, 0.5, 1.0), (0.5, 0.0, 0.5, 1.0)),                 # Nx2N
    3: ((0.0, 0.0, 0.5, 0.5), (0.5, 0.0, 0.5, 0.5),
        (0.0, 0.5, 0.5, 0.5), (0.5, 0.5, 0.5, 0.5)),                 # NxN
    4: ((0.0, 0.0, 1.0, 0.25), (0.0, 0.25, 1.0, 0.75)),             # 2NxnU
    5: ((0.0, 0.0, 1.0, 0.75), (0.0, 0.75, 1.0, 0.25)),             # 2NxnD
    6: ((0.0, 0.0, 0.25, 1.0), (0.25, 0.0, 0.75, 1.0)),             # nLx2N
    7: ((0.0, 0.0, 0.75, 1.0), (0.75, 0.0, 0.25, 1.0)),             # nRx2N
}


def _h264_pus(fb: VeyeFrameBlocks) -> np.ndarray:
    """H.264 prediction units: the macroblock partition rectangles
    (16x16 / 16x8 / 8x16 / 8x8 and intra/PCM), decoded from mb_type."""
    if fb.mb_type is None:
        return np.empty(0, dtype=BLOCK_DTYPE)
    unit = fb.block_unit
    mb = fb.mb_type
    out: list[tuple] = []
    for my in range(fb.grid_h):
        for mx in range(fb.grid_w):
            t = int(mb[my, mx])
            bx, by = mx * unit, my * unit
            for x, y, w, h, shape, pred in _partition(t, bx, by, unit):
                out.append((x, y, w, h, 0, pred, shape))
    return _pack(out, BLOCK_DTYPE)


def pus_from_frame(fb: VeyeFrameBlocks) -> np.ndarray:
    """Prediction units (BLOCK_DTYPE rectangles).

    HEVC: each CU is split into PUs per its PartMode (2Nx2N's single PU
    coincides with the CU). H.264: the macroblock's partition rectangles.
    AV1: the coding block is itself the prediction unit, so the PU rectangles
    coincide with the coding blocks.
    """
    if fb.codec_id == _CODEC_AV1:
        return _blocks_from_av1(fb)
    if fb.codec_id != _CODEC_HEVC:
        return _h264_pus(fb)
    if fb.cu_log2 is None or fb.part_mode is None:
        return np.empty(0, dtype=BLOCK_DTYPE)
    unit = fb.block_unit
    gh, gw = fb.cu_log2.shape
    cl = fb.cu_log2.astype(np.int32)
    pm = fb.part_mode
    pred = fb.pred

    mx = np.arange(gw, dtype=np.int32)[None, :]
    my = np.arange(gh, dtype=np.int32)[:, None]
    span = np.maximum(1, (1 << cl) // unit)
    origin = ((mx % span) == 0) & ((my % span) == 0)      # CU top-left cells
    ys, xs = np.nonzero(origin)
    if len(xs) == 0:
        return np.empty(0, dtype=BLOCK_DTYPE)

    cu_px = (1 << cl[ys, xs]).astype(np.int32)
    px = xs * unit
    py = ys * unit
    modes = pm[ys, xs].astype(np.int32)
    preds = (pred[ys, xs].astype(np.int32) if pred is not None
             else np.zeros(len(xs), dtype=np.int32))

    parts = []
    for mode, fracs in _PART_PUS.items():
        sel = modes == mode
        if not sel.any():
            continue
        spx, spy, scu, sp = px[sel], py[sel], cu_px[sel], preds[sel]
        for fx, fy, fw, fh in fracs:
            rec = np.empty(len(spx), dtype=BLOCK_DTYPE)
            rec["x"] = spx + (fx * scu).astype(np.int32)
            rec["y"] = spy + (fy * scu).astype(np.int32)
            rec["w"] = (fw * scu).astype(np.int32)
            rec["h"] = (fh * scu).astype(np.int32)
            rec["depth"] = 0
            rec["pred"] = sp
            rec["mode"] = mode
            parts.append(rec)
    if not parts:
        return np.empty(0, dtype=BLOCK_DTYPE)
    return np.concatenate(parts)


def _tu_rects(fb: VeyeFrameBlocks, chroma: bool) -> np.ndarray:
    """HEVC transform units (BLOCK_DTYPE rectangles) from the min-TB luma TU
    grid. Cells with no explicit TU (skip / no residual) fall back to the CU
    size. For chroma (assuming 4:2:0) a 4x4 luma TU has no 2x2 chroma TU --
    the four siblings share one 8x8-region chroma TU -- so the effective size
    is clamped to >= 8.
    """
    if (fb.codec_id != _CODEC_HEVC or fb.tu_log2 is None
            or fb.cu_log2 is None):
        return np.empty(0, dtype=BLOCK_DTYPE)
    tu = fb.tu_log2
    cu = fb.cu_log2
    unit = fb.tu_unit or fb.block_unit
    th, tw = tu.shape
    ratio = max(1, fb.block_unit // unit)
    cu_h, cu_w = cu.shape
    out: list[tuple] = []
    for my in range(th):
        py = my * unit
        for mx in range(tw):
            l = int(tu[my, mx])
            if l == 0:  # no explicit TU -> use the containing CU
                cy, cx = my // ratio, mx // ratio
                l = int(cu[cy, cx]) if cy < cu_h and cx < cu_w else 0
            if l == 0:
                continue
            if chroma and l < 3:
                l = 3  # 4:2:0: four 4x4 luma TUs share one 8x8 chroma TU
            size = 1 << l
            px = mx * unit
            if px % size or py % size:
                continue  # not the TU's top-left cell
            out.append((px, py, size, size, 0, 0, l))
    return _pack(out, BLOCK_DTYPE)


def _av1_tus(fb: VeyeFrameBlocks, chroma: bool) -> np.ndarray:
    """AV1 transform units (BLOCK_DTYPE rectangles) from the per-MI tx_size.

    tx_size is the coding block's transform size replicated across its 4x4 MI
    cells; tiling each block by that size at aligned top-left cells gives the
    TU rectangles. This is the block-level transform size (var-tx sub-splits
    are not separately inspected), so it is an approximation. For chroma under
    4:2:0 there is no sub-8 transform, so dimensions are clamped to >= 8.
    """
    if fb.codec_id != _CODEC_AV1 or fb.tx_size is None:
        return np.empty(0, dtype=BLOCK_DTYPE)
    tx = fb.tx_size
    unit = fb.block_unit
    out: list[tuple] = []
    for my in range(fb.grid_h):
        py = my * unit
        for mx in range(fb.grid_w):
            t = int(tx[my, mx])
            if t < 0 or t >= len(_AV1_TXSIZE_WH):
                continue
            tw, th = _AV1_TXSIZE_WH[t]
            if chroma:
                tw, th = max(8, tw), max(8, th)
            px = mx * unit
            if px % tw or py % th:
                continue  # not the TU's top-left cell
            out.append((px, py, tw, th, 0, 0, t))
    return _pack(out, BLOCK_DTYPE)


def tu_luma_from_frame(fb: VeyeFrameBlocks) -> np.ndarray:
    """Luma transform-unit rectangles."""
    if fb.codec_id == _CODEC_AV1:
        return _av1_tus(fb, chroma=False)
    return _tu_rects(fb, chroma=False)


def tu_chroma_from_frame(fb: VeyeFrameBlocks) -> np.ndarray:
    """Chroma transform-unit rectangles (4:2:0 derivation)."""
    if fb.codec_id == _CODEC_AV1:
        return _av1_tus(fb, chroma=True)
    return _tu_rects(fb, chroma=True)


def slice_lines_from_frame(fb: VeyeFrameBlocks) -> np.ndarray:
    """HEVC slice boundary segments [x1,y1,x2,y2] (px): the CTB edges where the
    slice id changes between neighbours. Returns an (N,4) int32 array."""
    sg = fb.slice_grid
    cs = fb.ctb_size
    if sg is None or cs <= 0:
        return np.empty((0, 4), dtype=np.int32)
    ch, cw = sg.shape
    out: list[tuple] = []
    for cy in range(ch):
        for cx in range(cw):
            sid = int(sg[cy, cx])
            if sid < 0:
                continue
            if cx > 0 and int(sg[cy, cx - 1]) != sid:  # left edge
                x = cx * cs
                out.append((x, cy * cs, x, (cy + 1) * cs))
            if cy > 0 and int(sg[cy - 1, cx]) != sid:  # top edge
                y = cy * cs
                out.append((cx * cs, y, (cx + 1) * cs, y))
    return np.array(out, dtype=np.int32) if out else np.empty((0, 4), np.int32)


def tile_lines_from_frame(fb: VeyeFrameBlocks) -> np.ndarray:
    """HEVC tile boundary segments [x1,y1,x2,y2] (px): internal tile column /
    row boundaries spanning the picture. Returns an (N,4) int32 array."""
    cbd = fb.tile_col_bd
    rbd = fb.tile_row_bd
    cs = fb.ctb_size
    if (len(cbd) <= 2 and len(rbd) <= 2):
        return np.empty((0, 4), dtype=np.int32)  # single tile: no internal bds
    if fb.slice_grid is not None and cs > 0:
        ch, cw = fb.slice_grid.shape
        w, h = cw * cs, ch * cs
    else:
        w = cbd[-1] if cbd else 0
        h = rbd[-1] if rbd else 0
    out: list[tuple] = []
    for x in cbd[1:-1]:               # internal vertical boundaries
        out.append((int(x), 0, int(x), int(h)))
    for y in rbd[1:-1]:               # internal horizontal boundaries
        out.append((0, int(y), int(w), int(y)))
    return np.array(out, dtype=np.int32) if out else np.empty((0, 4), np.int32)


def qp_grid_from_frame(fb: VeyeFrameBlocks) -> Optional[np.ndarray]:
    """QP grid at block_unit-pixel granularity (int16, -1 = unknown)."""
    if fb.qp is None:
        return None
    return fb.qp.astype(np.int16)


def mvs_from_frame(fb: VeyeFrameBlocks) -> np.ndarray:
    """Motion vectors (MV_DTYPE) for one frame, one per prediction region."""
    if fb.codec_id == _CODEC_AV1:
        return _mvs_from_av1(fb)
    return _mvs_from_hevc(fb)


def _mvs_from_av1(fb: VeyeFrameBlocks) -> np.ndarray:
    """Motion vectors for an AV1 frame, collapsed per coding block.

    Each inter block emits an L0 vector (ref_frame[0] >= 1) and, for compound
    prediction, an L1 vector (ref_frame[1] >= 1). ref_frame == 0 is INTRA_FRAME
    (intra block, no motion). Vectors are converted from eighth-pel to pixels.
    """
    if fb.bsize is None or fb.mv is None or fb.ref_idx is None:
        return np.empty(0, dtype=MV_DTYPE)
    unit = fb.block_unit
    bsize = fb.bsize
    ref = fb.ref_idx
    mv = fb.mv
    out: list[tuple] = []
    for my in range(fb.grid_h):
        py = my * unit
        for mx in range(fb.grid_w):
            bs = int(bsize[my, mx])
            if bs < 0 or bs >= len(_AV1_BSIZE_WH):
                continue
            bw, bh = _AV1_BSIZE_WH[bs]
            px = mx * unit
            if px % bw or py % bh:
                continue  # not the block's top-left cell
            if int(ref[my, mx, 0]) >= 1:  # 0 = INTRA_FRAME
                out.append((px, py, bw, bh, 0,
                            mv[my, mx, 0, 0] / _AV1_MV_SCALE,
                            mv[my, mx, 0, 1] / _AV1_MV_SCALE))
            if int(ref[my, mx, 1]) >= 1:  # compound L1
                out.append((px, py, bw, bh, 1,
                            mv[my, mx, 1, 0] / _AV1_MV_SCALE,
                            mv[my, mx, 1, 1] / _AV1_MV_SCALE))
    return _pack(out, MV_DTYPE)


def _mvs_from_hevc(fb: VeyeFrameBlocks) -> np.ndarray:
    """Motion vectors (MV_DTYPE) for an HEVC frame, one per prediction region.

    The motion field is sampled per min-CB. Cells are collapsed to their CU
    when the whole CU shares one MvField (the 2Nx2N case); CUs whose sub-cells
    differ (2NxN/Nx2N/NxN partitions) emit one vector per min-CB so the split
    is preserved. Vectors are converted from quarter-pel to luma pixels.

    Fully vectorized: at 1440p the per-cell Python loop cost ~90 ms/frame, which
    stuttered playback with the MV overlay on.
    """
    if fb.codec_id != _CODEC_HEVC or fb.pred_flag is None or fb.mv is None:
        return np.empty(0, dtype=MV_DTYPE)

    unit = fb.block_unit
    gh, gw = fb.pred_flag.shape
    pf = fb.pred_flag.astype(np.int32)
    mv = fb.mv                                   # (gh, gw, 2, 2) int16
    cu_log2 = fb.cu_log2.astype(np.int32)

    mx = np.arange(gw, dtype=np.int32)[None, :].repeat(gh, axis=0)
    my = np.arange(gh, dtype=np.int32)[:, None].repeat(gw, axis=1)
    span = np.maximum(1, (1 << cu_log2) // unit)  # min-CB cells per CU side
    ox = mx - (mx % span)                          # CU-origin cell coords
    oy = my - (my % span)
    is_origin = (mx == ox) & (my == oy)

    # A CU is uniform iff every one of its cells equals the CU's origin cell
    # (same pred_flag and same MVs). Count per-CU mismatches with a scatter-add.
    match = (pf == pf[oy, ox]) & (mv == mv[oy, ox]).all(axis=(2, 3))
    oidx = (oy * gw + ox).ravel()
    nmis = np.zeros(gh * gw, dtype=np.int64)
    np.add.at(nmis, oidx, (~match).ravel().astype(np.int64))
    cu_uniform = (nmis[oy * gw + ox] == 0)

    motion = pf > 0
    # Uniform CUs emit one vector at the origin (size = CU size); split CUs emit
    # one per motion min-CB (size = min-CB).
    cu_px = (1 << cu_log2).astype(np.int32)
    sel_uniform = is_origin & cu_uniform & motion
    sel_split = (~cu_uniform) & motion

    def records(sel, size):
        parts = []
        ys, xs = np.nonzero(sel)
        if len(xs) == 0:
            return parts
        flag = pf[ys, xs]
        for lst, bit in ((0, 1), (1, 2)):
            m = (flag & bit) != 0
            if not m.any():
                continue
            yy, xx = ys[m], xs[m]
            rec = np.empty(len(xx), dtype=MV_DTYPE)
            rec["x"] = xx * unit
            rec["y"] = yy * unit
            sz = size[yy, xx] if isinstance(size, np.ndarray) else size
            rec["w"] = sz
            rec["h"] = sz
            rec["list"] = lst
            rec["mv_x"] = mv[yy, xx, lst, 0] / _HEVC_MV_SCALE
            rec["mv_y"] = mv[yy, xx, lst, 1] / _HEVC_MV_SCALE
            parts.append(rec)
        return parts

    parts = records(sel_uniform, cu_px) + records(sel_split, unit)
    if not parts:
        return np.empty(0, dtype=MV_DTYPE)
    return np.concatenate(parts)


def _partition(t: int, bx: int, by: int, u: int):
    """Yield (x, y, w, h, shape, pred) sub-blocks for one macroblock."""
    if t & MB_TYPE_INTRA_PCM:
        yield (bx, by, u, u, SHAPE_IPCM, PredType.IPCM)
        return
    if t & _MB_TYPE_INTRA:
        shape = SHAPE_INTRA4 if (t & MB_TYPE_INTRA4x4) else SHAPE_INTRA16
        yield (bx, by, u, u, shape, PredType.INTRA)
        return
    pred = PredType.SKIP if (t & MB_TYPE_SKIP) else PredType.INTER
    if t & MB_TYPE_16x8:
        yield (bx, by, u, u // 2, SHAPE_16x8, pred)
        yield (bx, by + u // 2, u, u // 2, SHAPE_16x8, pred)
    elif t & MB_TYPE_8x16:
        yield (bx, by, u // 2, u, SHAPE_8x16, pred)
        yield (bx + u // 2, by, u // 2, u, SHAPE_8x16, pred)
    elif t & MB_TYPE_8x8:
        h = u // 2
        for dy in (0, h):
            for dx in (0, h):
                yield (bx + dx, by + dy, h, h, SHAPE_8x8, pred)
    else:
        shape = SHAPE_SKIP if (t & MB_TYPE_SKIP) else (
            SHAPE_DIRECT if (t & MB_TYPE_DIRECT2) else SHAPE_16x16)
        yield (bx, by, u, u, shape, pred)
