"""Reader for the .veblk block-analysis sidecar produced by veye_probe.

The sidecar is generated by the patched-FFmpeg helper (native/veye_probe.c).
It carries per-frame per-macroblock coding info (mb_type, QP) that mainline
FFmpeg does not expose. This module parses it and converts the codec
MB_TYPE bitmask into the codec-agnostic BLOCK_DTYPE partitions consumed by
the overlays.
"""

from __future__ import annotations

import struct
from dataclasses import dataclass
from typing import Optional

import numpy as np

from .schema import BLOCK_DTYPE, PredType

# Sidecar file header: u32 magic 'VEYE', u32 version, u32 n_frames
_FILE_MAGIC = 0x45594556  # bytes V E Y E
_FILE_HDR = struct.Struct("<III")
_ENTRY_HDR = struct.Struct("<II")  # frame_index, payload_size

# VeyeBlockInfoHeader: u32 magic 'VEBK', u16 ver, u16 rec_size, u32 codec_id,
#                      u32 grid_w, u32 grid_h, u32 block_unit, u32 n_records
_BLK_MAGIC = 0x4B424556  # bytes V E B K
_BLK_HDR = struct.Struct("<IHHIIIII")
# VeyeBlockRecord (H.264): u32 mb_type, i32 qp
_REC = np.dtype([("mb_type", "<u4"), ("qp", "<i4")])
# VeyeBlockRecordHEVC: u8 cu_log2, u8 pred, u8 intra_mode, u8 reserved, i32 qp
_REC_HEVC = np.dtype([
    ("cu_log2", "u1"), ("pred", "u1"), ("intra_mode", "u1"),
    ("reserved", "u1"), ("qp", "<i4"),
])

# codec_id values written into the header (AVCodecID, ABI-stable in practice).
_CODEC_H264 = 27
_CODEC_HEVC = 173

# FFmpeg MB_TYPE_* bits (libavcodec/mpegutils.h) — ABI-stable.
MB_TYPE_INTRA4x4 = 1 << 0
MB_TYPE_INTRA16x16 = 1 << 1
MB_TYPE_INTRA_PCM = 1 << 2
MB_TYPE_16x16 = 1 << 3
MB_TYPE_16x8 = 1 << 4
MB_TYPE_8x16 = 1 << 5
MB_TYPE_8x8 = 1 << 6
MB_TYPE_DIRECT2 = 1 << 8
MB_TYPE_P0L0 = 1 << 12
MB_TYPE_P1L0 = 1 << 13
MB_TYPE_P0L1 = 1 << 14
MB_TYPE_P1L1 = 1 << 15
MB_TYPE_SKIP = 1 << 17

_MB_TYPE_INTRA = MB_TYPE_INTRA4x4 | MB_TYPE_INTRA16x16 | MB_TYPE_INTRA_PCM
_MB_TYPE_L0 = MB_TYPE_P0L0 | MB_TYPE_P1L0
_MB_TYPE_L1 = MB_TYPE_P0L1 | MB_TYPE_P1L1

# Partition shape codes stored in BLOCK_DTYPE["mode"] for labeling.
SHAPE_16x16, SHAPE_16x8, SHAPE_8x16, SHAPE_8x8 = 0, 1, 2, 3
SHAPE_INTRA16, SHAPE_INTRA4, SHAPE_IPCM, SHAPE_SKIP, SHAPE_DIRECT = 4, 5, 6, 7, 8


@dataclass
class VeyeFrameBlocks:
    """Raw per-cell grid for one frame.

    H.264 cells are 16x16 macroblocks carrying an mb_type bitmask. HEVC
    cells are min coding blocks (typically 8x8); the variable CU size and
    prediction class live in the cu_log2/pred/intra_mode grids instead.
    """
    codec_id: int
    grid_w: int
    grid_h: int
    block_unit: int
    qp: np.ndarray                          # int32, shape (grid_h, grid_w)
    mb_type: Optional[np.ndarray] = None    # H.264: uint32 grid
    cu_log2: Optional[np.ndarray] = None    # HEVC: log2 CU size px
    pred: Optional[np.ndarray] = None       # HEVC: PredType per cell
    intra_mode: Optional[np.ndarray] = None  # HEVC: luma intra mode 0..34


def load_sidecar(path: str) -> Optional[dict[int, VeyeFrameBlocks]]:
    """Load a .veblk file into {frame_index: VeyeFrameBlocks}, or None."""
    try:
        with open(path, "rb") as f:
            data = f.read()
    except OSError:
        return None
    if len(data) < _FILE_HDR.size:
        return None
    magic, _ver, n_frames = _FILE_HDR.unpack_from(data, 0)
    if magic != _FILE_MAGIC:
        return None

    frames: dict[int, VeyeFrameBlocks] = {}
    off = _FILE_HDR.size
    for _ in range(n_frames):
        if off + _ENTRY_HDR.size > len(data):
            break
        frame_index, payload_size = _ENTRY_HDR.unpack_from(data, off)
        off += _ENTRY_HDR.size
        payload = data[off:off + payload_size]
        off += payload_size
        fb = _parse_payload(payload)
        if fb is not None:
            frames[frame_index] = fb
    return frames


def _parse_payload(payload: bytes) -> Optional[VeyeFrameBlocks]:
    if len(payload) < _BLK_HDR.size:
        return None
    (magic, _ver, rec_size, codec_id,
     grid_w, grid_h, block_unit, n_records) = _BLK_HDR.unpack_from(payload, 0)
    if magic != _BLK_MAGIC or grid_w == 0 or grid_h == 0:
        return None
    if n_records != grid_w * grid_h:
        return None

    if codec_id == _CODEC_HEVC:
        recs = np.frombuffer(payload, dtype=_REC_HEVC, count=n_records,
                             offset=_BLK_HDR.size)
        return VeyeFrameBlocks(
            codec_id, grid_w, grid_h, block_unit,
            qp=recs["qp"].reshape(grid_h, grid_w).copy(),
            cu_log2=recs["cu_log2"].reshape(grid_h, grid_w).copy(),
            pred=recs["pred"].reshape(grid_h, grid_w).copy(),
            intra_mode=recs["intra_mode"].reshape(grid_h, grid_w).copy(),
        )

    recs = np.frombuffer(payload, dtype=_REC, count=n_records,
                         offset=_BLK_HDR.size)
    return VeyeFrameBlocks(
        codec_id, grid_w, grid_h, block_unit,
        qp=recs["qp"].reshape(grid_h, grid_w).copy(),
        mb_type=recs["mb_type"].reshape(grid_h, grid_w).copy(),
    )


def blocks_from_frame(fb: VeyeFrameBlocks) -> np.ndarray:
    """Decode a frame's per-cell grid into BLOCK_DTYPE partitions."""
    if fb.codec_id == _CODEC_HEVC:
        return _blocks_from_hevc(fb)

    unit = fb.block_unit
    out: list[tuple] = []
    mb = fb.mb_type
    for my in range(fb.grid_h):
        for mx in range(fb.grid_w):
            t = int(mb[my, mx])
            bx, by = mx * unit, my * unit
            for x, y, w, h, shape, pred in _partition(t, bx, by, unit):
                out.append((x, y, w, h, 0, pred, shape))
    arr = np.empty(len(out), dtype=BLOCK_DTYPE)
    for i, rec in enumerate(out):
        arr[i] = rec
    return arr


def _blocks_from_hevc(fb: VeyeFrameBlocks) -> np.ndarray:
    """Collapse the min-CB grid back into the HEVC coding-unit quadtree.

    Every min-CB cell carries the log2 size of the CU it belongs to. A CU
    is aligned to its own size, so the cell at the CU's top-left corner is
    the unique cell where both pixel coordinates are multiples of the CU
    size; we emit one partition rectangle there. The mode field stores
    cu_log2 for labeling.
    """
    unit = fb.block_unit
    cu_log2 = fb.cu_log2
    pred = fb.pred
    out: list[tuple] = []
    for my in range(fb.grid_h):
        py = my * unit
        for mx in range(fb.grid_w):
            cl = int(cu_log2[my, mx])
            cu_px = 1 << cl
            px = mx * unit
            if px % cu_px or py % cu_px:
                continue  # not the top-left cell of this CU
            out.append((px, py, cu_px, cu_px, 0, int(pred[my, mx]), cl))
    arr = np.empty(len(out), dtype=BLOCK_DTYPE)
    for i, rec in enumerate(out):
        arr[i] = rec
    return arr


def _partition(t: int, bx: int, by: int, u: int):
    """Yield (x, y, w, h, shape, pred) sub-blocks for one macroblock."""
    if t & MB_TYPE_INTRA_PCM:
        yield (bx, by, u, u, SHAPE_IPCM, PredType.IPCM)
        return
    if t & _MB_TYPE_INTRA:
        shape = SHAPE_INTRA4 if (t & MB_TYPE_INTRA4x4) else SHAPE_INTRA16
        yield (bx, by, u, u, shape, PredType.INTRA)
        return
    pred = PredType.SKIP if (t & MB_TYPE_SKIP) else PredType.INTER
    if t & MB_TYPE_16x8:
        yield (bx, by, u, u // 2, SHAPE_16x8, pred)
        yield (bx, by + u // 2, u, u // 2, SHAPE_16x8, pred)
    elif t & MB_TYPE_8x16:
        yield (bx, by, u // 2, u, SHAPE_8x16, pred)
        yield (bx + u // 2, by, u // 2, u, SHAPE_8x16, pred)
    elif t & MB_TYPE_8x8:
        h = u // 2
        for dy in (0, h):
            for dx in (0, h):
                yield (bx + dx, by + dy, h, h, SHAPE_8x8, pred)
    else:
        shape = SHAPE_SKIP if (t & MB_TYPE_SKIP) else (
            SHAPE_DIRECT if (t & MB_TYPE_DIRECT2) else SHAPE_16x16)
        yield (bx, by, u, u, shape, pred)
